### PR TITLE
fix: keyboard covers emoji search results

### LINKED ISSUE #2261: Keyboard doesn't dismiss when scrolling the object emoji picker
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

When the user opens the emoji picker (to select an object's icon) and enters a search query, then the keyboard is partially covering the emoji grid. However if the user then scrolls the grid the keyboard does not dismiss and continues to cover the emojis. If the user scrolls all the way to the bottom, they can not see the last emojis in the grid.

Simulator Screen Recording - iPhone 16 - 2024-10-23 at 22 52 18

### Expected Behavior

When the grid is scrolled then the keyboard is dismissed.

Simulator Screen Recording - iPhone 16 - 2024-10-23 at 22 54 23

### Steps To Reproduce

1. Tap on the icon of an object
2. When the emoji picker is shown, enter a search query. The keyboard should be visible.
3. Scroll the emoji grid.

### Environment

```markdown
- OS: iOS 18
- Version: 0.32.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by johnxnguyen**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents
Fixes #2261 

### Mobile & Desktop Screenshots/Recordings

Before:
Simulator Screen Recording - iPhone 16 - 2024-10-23 at 22 52 18

After:
Simulator Screen Recording - iPhone 16 - 2024-10-23 at 22 54 23

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by johnxnguyen** [comment]
I have read the CLA Document and I hereby sign the CLA

File: Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/Emoji/EmojiGridView.swift [hunk 1]
```diff
@@ -63,11 +63,8 @@ struct EmojiGridView: View {
     private func makeEmojiGrid(groups: [EmojiGroup]) -> some View {
         ScrollView(showsIndicators: false) {
             makeGridView(groups: groups)
-        }.gesture(
-            DragGesture().onChanged { _ in
-                UIApplication.shared.hideKeyboard()
-            }
-        )
+        }
+        .scrollDismissesKeyboard(.immediately)
```
Comment (mgolovko) [inline Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/Emoji/EmojiGridView.swift:67]: maybe use interactive? If I want to search and view the results, it would be better if the keyboard doesn't hide

Comment (johnxnguyen) [reply Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/Emoji/EmojiGridView.swift]: Sure, done in 2cc9397adf988dea517ce8c4ebc5893de244d8ec

**Review by ignatovv — APPROVED** [review]

**Comment by mgolovko** [comment]
@johnxnguyen can you merge or rebase on develop?

**Comment by johnxnguyen** [comment]
@mgolovko sure, done!

**Comment by mgolovko** [comment]
Your changes have been passed to qa
